FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o task-processor .

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/task-processor .

EXPOSE 8080

CMD ["./task-processor"]
